### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat-bot/deltachat-node-bot-base#4]

**Comment by pabzm** [comment]
No ticket without description, please.

**Comment by pabzm** [comment]
And as background: I don't see a benefit to publishing it on npmjs.com. People can use the code easily by using the github-URL as dependency, too. And this is very specific code, only interesting to people working DC-related stuff. Additionally NPM Inc. is not exactly a nice and friendly company that should be supported.
